// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1beUOIsk4Y10q5Wl381O1kXzbvxLxY8U',
    appId: '1:853737499209:web:690938e5d24b7062282d98',
    messagingSenderId: '853737499209',
    projectId: 'social-media-app-eba3c',
    authDomain: 'social-media-app-eba3c.firebaseapp.com',
    storageBucket: 'social-media-app-eba3c.appspot.com',
    measurementId: 'G-V8H02CQK9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAwtk4mVOUcY6vHvkkQLtuvkvgy73KAAo',
    appId: '1:853737499209:android:79ad0700ef49a90a282d98',
    messagingSenderId: '853737499209',
    projectId: 'social-media-app-eba3c',
    storageBucket: 'social-media-app-eba3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd-kXPijpNqlS5x0I-54JWMPHWbwfMa_o',
    appId: '1:853737499209:ios:5c96e3a8bb5d34ce282d98',
    messagingSenderId: '853737499209',
    projectId: 'social-media-app-eba3c',
    storageBucket: 'social-media-app-eba3c.appspot.com',
    iosClientId: '853737499209-peb1l5lca9ifs3b4k0hjanvvvip4od94.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd-kXPijpNqlS5x0I-54JWMPHWbwfMa_o',
    appId: '1:853737499209:ios:5c96e3a8bb5d34ce282d98',
    messagingSenderId: '853737499209',
    projectId: 'social-media-app-eba3c',
    storageBucket: 'social-media-app-eba3c.appspot.com',
    iosClientId: '853737499209-peb1l5lca9ifs3b4k0hjanvvvip4od94.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
